// All Action type will handle with Store
// easily Access
const TOGGLE_APP_LOADING = 'TOGGLE_APP_LOADING';

const NEWS_ACTIONS = {
  SET_NEWS_STORYS_IDS: 'SET_NEWS_STORYS_IDS',
  SET_NEWS_STORYS_ITEM: 'SET_NEWS_STORYS_ITEM',
  SET_COMMENTS_ITEM: 'SET_COMMENTS_ITEM',
  SET_NEWS_INDICATOR: 'SET_NEWS_INDICATOR',
};

const JOB_ACTIONS = {
  SET_JOB_STORYS_IDS: 'SET_JOB_STORYS_IDS',
  SET_JOB_STORYS_ITEM: 'SET_JOB_STORYS_ITEM',
};

export default {
  TOGGLE_APP_LOADING,
  NEWS_ACTIONS,
  JOB_ACTIONS,
};
